name: build windows release manually triggered 
  
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'making mlmat'
        # Default value if no value is explicitly provided
        default: 'make'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  build_windows:
    name: build windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: build arma
      run: | 
        cd source/armadillo-code
        mkdir build
        cd build
        cmake -DBUILD_SHARED_LIBS=OFF -DOPENBLAS_PROVIDES_LAPACK=true -G "Visual Studio 17 2022" -A x64 ..
        cmake --build . --config Release
    - name: build ensmallen
      run: | 
        cd source/ensmallen
        mkdir build
        cd build
        cmake -DLAPACK_LIBRARY="../../armadillo-code/examples/lib_win64/libopenblas.lib" -DBLAS_LIBRARY="../../armadillo-code/examples/lib_win64/libopenblas.lib" -DARMADILLO_INCLUDE_DIR="../../armadillo-code/include" ..
    - name: build mlpack
      run: | 
        cd source/mlpack
        mkdir build
        cd build
        cmake -DBUILD_SHARED_LIBS=OFF -DBUILD_CLI_EXECUTABLES=OFF -DBUILD_PYTHON_BINDINGS=OFF -DBUILD_JULIA_BINDINGS=OFF -DBUILD_GO_BINDINGS=OFF -DBUILD_R_BINDINGS=OFF -DARMADILLO_LIBRARY="../../armadillo-code/build/Release/armadillo.lib" -DENSMALLEN_INCLUDE_DIR="../../ensmallen/include" -DARMADILLO_INCLUDE_DIR="../../armadillo-code/include" -DCEREAL_INCLUDE_DIR="../../cereal/include" -G "Visual Studio 17 2022" -A x64 ..
        cmake --build . --config Release
    - name: build mlmat
      run: | 
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 ..
        cmake --build . --config Release

    - name: make zip file
      run: |
        mkdir mlmat
        mv ./examples ./mlmat
        mv ./extras ./mlmat
        mv ./externals ./mlmat
        mv ./help ./mlmat 
        mv ./init ./mlmat
        mv ./javascript ./mlmat
        mv ./misc ./mlmat
        mv ./patchers ./mlmat
        mv LICENSE ./mlmat
        mv README.md ./mlmat
        mv package-info.json ./mlmat
        zip -r mlmat mlmat
    - name: Create Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: "v0.5.0"
        files: mlmat_windows.zip
        token: ${{ secrets.THIS_REPO }}

    
    
